# Site settings
author: Joshua Collins
title: A New Beginning
header-img: img/home-bg.png
email: pc.refuge@gmail.com
copyright_name: Joshua Collins
description: > # this means to ignore newlines until "baseurl:"
  The journey of a new coder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  builtbyjosh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
